runtime: nodejs
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
env_variables:
  NODE_ENV: production
network:
  forwarded_ports:
  - 65080
  instance_tag: websocket
  session_affinity: true
handlers:
  - url: /static
    static_dir: build/static
  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$
  - url: .*
    static_files: build/index.html
    upload: build/index.html

# handlers:
#   - url: /(.*\..+)$
#     static_files: build/\1
#     upload: build/(.*\..+)$
#   - url: /.*
#     static_files: build/index.html
#     upload: build/index.htm