runtime: nodejs
env: flex
network:
  forwarded_ports:
  - 65080
  instance_tag: websocket
  session_affinity: true
handlers:
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10